# Generated by Django 3.0.8 on 2020-07-07 19:07

import Account.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of Batch', max_length=50, verbose_name='Name')),
                ('branch', models.CharField(max_length=50, verbose_name='Branch')),
                ('year', models.IntegerField(verbose_name='Year')),
                ('semester', models.IntegerField(verbose_name='Semester')),
            ],
            options={
                'verbose_name': 'Batch',
                'verbose_name_plural': 'Batchs',
            },
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('code', models.SlugField(max_length=20, primary_key=True, serialize=False, unique=True, verbose_name='Paper Code')),
            ],
            options={
                'verbose_name': 'Result',
                'verbose_name_plural': 'Results',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('regno', models.IntegerField(primary_key=True, serialize=False, unique=True, verbose_name='Registartion Number')),
                ('name', models.CharField(help_text="Student's Name", max_length=120, verbose_name='Name')),
                ('email', models.EmailField(help_text="Studnet's Student", max_length=254, unique=True, verbose_name='Email')),
                ('phone', models.CharField(help_text="Student's phone number", max_length=10, unique=True, validators=[Account.models.phoneVerify], verbose_name='Phone')),
                ('active', models.BooleanField(default=False, verbose_name='Active')),
                ('auth', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='studentAuth', to=settings.AUTH_USER_MODEL, verbose_name="Student's Auth")),
                ('batch', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='batchs', to='Account.Batch', verbose_name='Batch')),
            ],
            options={
                'verbose_name': 'Student',
                'verbose_name_plural': 'Students',
            },
        ),
        migrations.CreateModel(
            name='Studentexam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mark', models.IntegerField(default=0, verbose_name='Mark')),
                ('result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Account.Result', verbose_name='Examination')),
                ('student', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Account.Student', verbose_name='Student')),
            ],
        ),
        migrations.AddField(
            model_name='result',
            name='students',
            field=models.ManyToManyField(related_name='studExam', through='Account.Studentexam', to='Account.Student', verbose_name='Students'),
        ),
    ]
