# Generated by Django 3.0.8 on 2020-07-31 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0004_result_active'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='studentexam',
            options={'ordering': ('mark',)},
        ),
    ]
